export const curriculum = [
  {
    id: "welcome",
    title: "Orientation (Mindset & Reality)",
    lessonIds: [
      "welcome-to-csharp",
      "what-programming-actually-is-cs",
      "what-csharp-can-do",
      "csharp-vs-java-vs-python",
      "the-dotnet-runtime",
      "how-this-course-works-cs",
      "what-it-means-to-be-a-csharp-developer",
    ],
  },
  {
    id: "prerequisites",
    title: "Prerequisites: Your Real Development Environment",
    lessonIds: [
      "installing-the-dotnet-sdk",
      "sdk-vs-runtime",
      "vscode-csharp-dev-kit",
      "visual-studio-community",
      "terminal-basics-dotnet",
      "first-console-project",
      "csproj-and-solution-files",
      "common-setup-errors-cs",
    ],
  },
  {
    id: "csharp-fundamentals",
    title: "C# Fundamentals (Core Language Fluency)",
    lessonIds: [
      "no-ai-learn-first-cs",
      "hello-world-every-token",
      "variables-types-declarations-cs",
      "value-types-vs-reference-types",
      "strings-and-interpolation",
      "operators-and-math-cs",
      "conditionals-cs",
      "loops-cs",
      "arrays-cs",
      "methods-cs",
      "reading-input-cs",
      "type-casting-cs",
      "mini-project-number-guessing-game-cs",
      "mini-project-simple-calculator-cs",
      "mini-project-grade-calculator",
    ],
  },
  {
    id: "thinking-in-systems",
    title: "Thinking in Systems (Advanced Fundamentals)",
    lessonIds: [
      "tracing-execution-cs",
      "state-change-over-time-cs",
      "scope-variable-lifetime-cs",
      "vs-debugger",
      "errors-types-cs",
      "reading-exception-stack-traces",
      "refactoring-code-clarity-cs",
      "problem-decomposition-cs",
    ],
  },
  {
    id: "console-applications",
    title: "Console Applications (Real Software, No Frameworks)",
    lessonIds: [
      "what-is-a-console-application-cs",
      "readline-vs-command-line-args",
      "program-structure-entry-points-cs",
      "designing-user-interaction-cs",
      "exception-handling-cli-cs",
      "organizing-larger-console-apps-cs",
      "intro-to-verification-cs",
      "mini-project-todo-cli-cs",
      "mini-project-quiz-game-cs",
      "mini-project-adventure-game-cs",
    ],
  },
  {
    id: "files-data",
    title: "Files, Data & the Operating System",
    lessonIds: [
      "reading-files-cs",
      "writing-files-cs",
      "working-with-csv-cs",
      "directories-and-paths-cs",
      "handling-missing-files-cs",
      "automating-repetitive-tasks-cs",
      "working-with-json-cs",
      "cross-platform-paths",
      "mini-project-csv-report-cs",
      "mini-project-backup-script-cs",
      "mini-project-file-renaming-tool-cs",
      "mini-project-log-analyzer-cs",
    ],
  },
  {
    id: "oop",
    title: "Object-Oriented Programming (Foundations)",
    lessonIds: [
      "why-oop-cs",
      "classes-instances-constructors-cs",
      "fields-properties-auto-properties",
      "methods-and-this-cs",
      "access-modifiers-cs",
      "static-keyword-cs",
      "object-initializers-named-args",
      "tostring-equals-gethashcode",
      "when-not-to-use-oop-cs",
      "mini-project-refactor-todo-cli-cs",
      "mini-project-library-catalogue-cs",
      "mini-project-bank-account-cs",
    ],
  },
  {
    id: "interfaces-abstraction",
    title: "Interfaces, Abstraction & Advanced OOP",
    lessonIds: [
      "inheritance-cs",
      "method-overriding-base",
      "abstract-classes-cs",
      "interfaces-cs",
      "polymorphism-cs",
      "is-as-pattern-matching",
      "composition-vs-inheritance-cs",
      "enums-cs",
      "records-cs",
      "sealed-classes",
      "mini-project-shape-hierarchy-cs",
      "mini-project-payment-system-cs",
      "mini-project-notification-service-cs",
    ],
  },
  {
    id: "collections-linq",
    title: "Collections, LINQ & Generics",
    lessonIds: [
      "why-collections-cs",
      "list-and-linkedlist-cs",
      "dictionary-cs",
      "hashset-sortedset",
      "queue-and-stack-cs",
      "iterating-collections-cs",
      "generics-cs",
      "ienumerable-icomparable",
      "intro-to-linq",
      "linq-filtering-projecting-aggregating",
      "choosing-right-collection-cs",
      "mini-project-word-frequency-cs",
      "mini-project-student-roster-cs",
      "mini-project-generic-stack-cs",
      "mini-project-linq-pipeline",
    ],
  },
  {
    id: "testing-xunit",
    title: "Testing with xUnit",
    lessonIds: [
      "why-testing-matters-cs",
      "first-test-xunit",
      "assertions-test-structure-cs",
      "testing-edge-cases-cs",
      "organizing-tests-cs",
      "intro-to-moq",
      "test-coverage-cs",
      "mini-project-bank-account-tests-cs",
      "mini-project-tdd-exercise-cs",
    ],
  },
  {
    id: "async-concurrency",
    title: "Async, Tasks & Concurrency",
    lessonIds: [
      "why-async",
      "tasks-cs",
      "async-and-await",
      "race-conditions-cs",
      "configure-await",
      "task-when-all-when-any",
      "cancellation-token",
      "thread-safe-collections-cs",
      "mini-project-async-file-processor",
      "mini-project-parallel-api-caller",
    ],
  },
  {
    id: "project-structure-nuget",
    title: "Project Structure & NuGet",
    lessonIds: [
      "scripts-vs-software-cs",
      "dotnet-project-structure",
      "class-libraries-vs-apps",
      "intro-to-nuget",
      "managing-dependencies-cs",
      "separating-concerns-cs",
      "reusable-utility-classes-cs",
      "mini-project-multi-project-solution",
      "mini-project-nuget-dependency-app",
    ],
  },
  {
    id: "apis-http",
    title: "APIs & HTTP Requests",
    lessonIds: [
      "what-is-an-api-cs",
      "http-basics-cs",
      "httpclient",
      "parsing-json-cs",
      "reading-api-docs-cs",
      "authentication-cs",
      "error-handling-network-cs",
      "mini-project-weather-cli-cs",
      "mini-project-github-fetcher-cs",
      "mini-project-currency-converter-cs",
    ],
  },
  {
    id: "git-workflow",
    title: "Professional Workflow (Git & Collaboration)",
    lessonIds: [
      "what-is-version-control-cs",
      "git-basics-cs",
      "github-fundamentals-cs",
      "commits-history-gitignore-cs",
      "branches-experimentation-cs",
      "pull-requests-code-review-cs",
      "fixing-mistakes-safely-cs",
      "committing-to-github-cs",
    ],
  },
  {
    id: "standard-library",
    title: "Standard Library Essentials",
    lessonIds: [
      "datetime-datetimeoffset",
      "timezoneinfo",
      "string-utilities-cs",
      "regex-cs",
      "guid-and-random",
      "environment-and-path",
      "reading-dotnet-docs",
    ],
  },
  {
    id: "real-world",
    title: "C# in the Real World (Choose a Track)",
    lessonIds: [
      "which-track-is-right-for-me-cs",
      "track-backend-apis-aspnet",
      "track-desktop-maui",
      "track-game-development-unity",
      "track-data-engineering-cs",
      "track-enterprise-cloud-azure",
      "track-developer-tooling-cli-cs",
    ],
  },
  {
    id: "capstone",
    title: "Capstone Projects (Proof of Fluency)",
    lessonIds: [
      "capstone-cli-tool-cs",
      "capstone-rest-api-cs",
      "capstone-desktop-app",
      "capstone-data-pipeline-cs",
      "capstone-developer-tool-cs",
      "capstone-unity-game",
    ],
  },
];
