/**
 * Curriculum: ordered list of modules and their lesson IDs.
 * Add new modules here and create a matching folder under lessons/<moduleId>/ with an index.js that exports the lessons array.
 * Lesson order is determined by the order of lessonIds in each module.
 */
export const curriculum = [
  {
    id: "welcome",
    title: "Orientation (Mindset & Reality)",
    lessonIds: [
      "welcome-intro",
      "intro-what-programming-actually-is",
      "intro-what-python-can-do",
      "intro-how-this-course-works",
      "intro-what-does-it-mean-to-be-a-python-developer"
    ],
  },
  {
    id: "prerequisites",
    title: "Prerequisites: Your Real Development Environment",
    lessonIds: [
      "installing-python",
      "verify-python",
      "install-VScode",
      "VScode-Tour",
      "terminal-basics",
      "common-setup-issues",
    ],
  },
  {
    id: "python-fundamentals",
    title: "Python Fundamentals (Core Language Fluency)",
    lessonIds: [
      "using-ai-with-discipline",
      "hello-world",
      "comments",
      "numbers-and-math",
      "variables-and-types",
      "data-types",
      "casting",
      "operators",
      "booleans-and-conditions",
      "match",
      "lists",
      "tuples",
      "dictionaries-sets",
      "none-type",
      "loops",
      "range",
      "iterators",
      "functions",
      "modules-imports",
      "try-except",
      "strings-and-format",
      "input-output",
      "mini-projects-introduction",
      "mini-project-number-guessing-game",
      "mini-project-text-formatter",
      "mini-project-simple-menu",
    ],
  },
  {
    id: "thinking-in-systems",
    title: "Thinking in Systems (Advanced Fundamentals)",
    lessonIds: [
      "tracing-execution",
      "state-change-over-time",
      "scope-lifetime",
      "errors-debugging",
      "refactoring-code-clarity",
      "problem-decomposition",
    ],
  },
  {
    id: "git-workflow",
    title: "Professional Workflow (Git & Collaboration)",
    lessonIds: [
      "what-is-version-control",
      "git-basics",
      "github-fundamentals",
      "commits-history",
      "branches-experimentation",
      "fixing-mistakes-safely",
      "committing-project-to-github",
    ],
  },
  {
    id: "console-applications",
    title: "Console Applications (Real Software, No Frameworks)",
    lessonIds: [
      "what-is-a-console-application",
      "input-vs-command-line-arguments",
      "program-structure-entry-points",
      "designing-user-interaction-terminal",
      "error-handling-cli-programs",
      "organizing-larger-console-apps",
      "intro-to-verification",
      "project-todo-cli",
      "project-quiz-game",
      "project-text-based-game",
    ],
  },
  {
    id: "files-data",
    title: "Files, Data & the Operating System",
    lessonIds: [
      "reading-files",
      "writing-files",
      "working-with-csv-text-data",
      "directories-paths",
      "handling-missing-broken-files",
      "automating-repetitive-tasks",
      "working-with-json",
      "project-csv-report-generator",
      "project-backup-script",
      "project-file-renaming-tool",
      "project-log-file-analyzer",
    ],
  },
  {
    id: "oop",
    title: "Object-Oriented Programming",
    lessonIds: [
      "why-oop",
      "classes-instances-init",
      "methods-and-self",
      "attributes-instance-vs-class",
      "inheritance-reuse",
      "dunder-methods",
      "composition-vs-inheritance",
      "when-not-to-use-oop",
      "project-refactor-todo-cli-classes",
      "project-library-catalogue",
      "project-bank-account-simulator",
    ],
  },
  {
    id: "environments-quality",
    title: "Environments, Dependencies & Code Quality",
    lessonIds: [
      "venv",
      "managing-packages-pip",
      "requirements-txt",
      "type-hints-annotations",
      "linting-formatting",
    ],
  },
  {
    id: "apis-http",
    title: "APIs & HTTP Requests",
    lessonIds: [
      "what-is-an-api",
      "http-basics",
      "requests-library",
      "working-with-json-responses",
      "reading-api-documentation",
      "authentication-api-keys",
      "error-handling-network-requests",
      "project-weather-cli",
      "project-github-repo-fetcher",
      "project-currency-converter",
    ],
  },
  {
    id: "project-structure-scaling-python",
    title: "Project Structure & Scaling Python",
    lessonIds: [
      "scripts-vs-software",
      "modules-vs-packages",
      "clean-imports",
      "separating-concerns",
      "reusability-maintainability",
      "project-multi-file-console-app",
      "project-reusable-utility-package",
    ],
  },
  {
    id: "testing",
    title: "Testing Your Code",
    lessonIds: [
      "why-testing-matters",
      "first-test-pytest",
      "assertions-test-structure",
      "testing-edge-cases",
      "organizing-tests",
      "intro-to-mocking",
      "project-test-suite-cli-app",
    ],
  },
  {
    id: "standard-library-essentials",
    title: "Standard Library Essentials",
    lessonIds: [
      "pathlib-modern-file-paths",
      "datetime-dates-times-deltas",
      "collections-core-tools",
      "itertools-working-with-sequences",
      "regex-basics",
      "reading-standard-library-docs",
    ],
  },
  {
    id: "real-world",
    title: "Python in the Real World (Choose a Track)",
    lessonIds: [
      "which-track-is-right-for-me",
      "track-automation-scripting",
      "track-backend-apis",
      "track-data-analysis",
      "track-ai-ml-foundations",
      "track-game-tools",
      "track-developer-tooling",
    ],
  },
  {
    id: "capstone",
    title: "Capstone Projects (Proof of Fluency)",
    lessonIds: [
      "capstone-full-featured-cli",
      "capstone-automation-suite",
      "capstone-data-pipeline",
      "capstone-backend-service",
      "capstone-developer-tool",
    ],
  },
];
