/**
 * Curriculum: ordered list of modules and their lesson IDs.
 * Add new modules here and create a matching folder under lessons/<moduleId>/ with an index.js that exports the lessons array.
 * Lesson order is determined by the order of lessonIds in each module.
 */
export const curriculum = [
  {
    id: "welcome",
    title: "Orientation (Mindset & Reality)",
    lessonIds: [
      "welcome-to-java",
      "what-programming-actually-is",
      "what-java-can-do",
      "how-java-differs-from-python",
      "the-jvm",
      "how-this-course-works",
      "what-it-means-to-be-a-java-developer",
    ],
  },
  {
    id: "prerequisites",
    title: "Prerequisites: Your Real Development Environment",
    lessonIds: [
      "installing-the-jdk",
      "jdk-vs-jre",
      "installing-intellij",
      "intellij-tour",
      "terminal-basics-for-java",
      "first-java-project",
      "common-setup-errors",
    ],
  },
  {
    id: "java-fundamentals",
    title: "Java Fundamentals (Core Language Fluency)",
    lessonIds: [
      "no-ai-learn-first",
      "hello-world-long-way",
      "variables-types-declarations",
      "primitive-types",
      "strings-reference-type",
      "operators-math",
      "conditionals",
      "switch-statements",
      "loops",
      "arrays",
      "methods",
      "reading-input-scanner",
      "type-casting",
      "mini-project-number-guessing-game",
      "mini-project-simple-calculator",
      "mini-project-text-menu",
    ],
  },
  {
    id: "thinking-in-systems",
    title: "Thinking in Systems (Advanced Fundamentals)",
    lessonIds: [
      "tracing-execution",
      "state-change-over-time",
      "scope-variable-lifetime",
      "java-debugger",
      "errors-types",
      "reading-stack-traces",
      "refactoring-code-clarity",
      "problem-decomposition",
    ],
  },
  {
    id: "oop-foundations",
    title: "Object-Oriented Programming Part 1 (Foundations)",
    lessonIds: [
      "what-is-oop",
      "classes-and-objects",
      "fields-and-constructors",
      "methods-and-this",
      "access-modifiers",
      "encapsulation",
      "static-keyword",
      "tostring-equals-hashcode",
      "packages-and-imports",
      "mini-project-bank-account",
      "mini-project-student-grade-tracker",
      "mini-project-inventory-system",
    ],
  },
  {
    id: "oop-advanced",
    title: "Object-Oriented Programming Part 2 (Advanced OOP)",
    lessonIds: [
      "inheritance",
      "method-overriding-super",
      "abstract-classes",
      "interfaces",
      "polymorphism",
      "instanceof-pattern-matching",
      "composition-vs-inheritance",
      "enums",
      "records",
      "when-not-to-use-inheritance",
      "mini-project-shape-hierarchy",
      "mini-project-payment-system",
      "mini-project-notification-service",
    ],
  },
  {
    id: "collections-generics",
    title: "Collections & Generics",
    lessonIds: [
      "why-collections",
      "collections-framework-overview",
      "arraylist-linkedlist",
      "hashmap-linkedhashmap",
      "hashset-treeset",
      "iterating-collections",
      "generics",
      "comparable-comparator",
      "sorting-searching",
      "choosing-right-collection",
      "mini-project-word-frequency",
      "mini-project-student-roster",
      "mini-project-generic-stack",
    ],
  },
  {
    id: "files-io-exceptions",
    title: "File I/O, Exceptions & Error Handling",
    lessonIds: [
      "reading-files",
      "writing-files",
      "working-with-paths",
      "reading-writing-csv",
      "working-with-json",
      "exception-handling",
      "checked-unchecked-exceptions",
      "custom-exceptions",
      "try-with-resources",
      "handling-missing-corrupt-files",
      "mini-project-csv-report",
      "mini-project-file-backup",
      "mini-project-log-analyzer",
    ],
  },
  {
    id: "project-structure-build-tools",
    title: "Project Structure & Build Tools",
    lessonIds: [
      "scripts-vs-software",
      "java-project-structure",
      "packages-module-system",
      "intro-to-maven",
      "managing-dependencies-maven",
      "intro-to-gradle",
      "separating-concerns",
      "reusable-utility-classes",
      "mini-project-convert-to-maven",
      "mini-project-multi-module-app",
    ],
  },
  {
    id: "testing-junit",
    title: "Testing with JUnit",
    lessonIds: [
      "why-testing-matters",
      "first-test-junit5",
      "assertions-test-structure",
      "testing-edge-cases",
      "organizing-tests-maven",
      "intro-to-mockito",
      "test-coverage",
      "mini-project-bank-account-tests",
      "mini-project-tdd-exercise",
    ],
  },
  {
    id: "concurrency",
    title: "Concurrency Basics",
    lessonIds: [
      "what-is-concurrency",
      "threads",
      "runnable-callable",
      "race-conditions",
      "synchronized-keyword",
      "executor-service",
      "futures-completable-future",
      "thread-safe-collections",
      "mini-project-parallel-file-processor",
      "mini-project-producer-consumer",
    ],
  },
  {
    id: "apis-http",
    title: "APIs & HTTP Requests",
    lessonIds: [
      "what-is-an-api",
      "http-basics",
      "java-httpclient",
      "parsing-json-responses",
      "reading-api-documentation",
      "authentication-api-keys",
      "error-handling-network",
      "mini-project-weather-cli",
      "mini-project-github-fetcher",
      "mini-project-currency-converter",
    ],
  },
  {
    id: "git-workflow",
    title: "Professional Workflow (Git & Collaboration)",
    lessonIds: [
      "what-is-version-control",
      "git-basics",
      "github-fundamentals",
      "commits-history-gitignore",
      "branches-experimentation",
      "pull-requests-code-review",
      "fixing-mistakes-safely",
      "committing-project-github",
    ],
  },
  {
    id: "standard-library-essentials",
    title: "Standard Library Essentials",
    lessonIds: [
      "java-time",
      "optional",
      "streams-lambda",
      "functional-interfaces",
      "string-utilities",
      "math-random-uuid",
      "reading-javadoc",
    ],
  },
  {
    id: "real-world",
    title: "Java in the Real World (Choose a Track)",
    lessonIds: [
      "which-track-is-right-for-me",
      "track-backend-apis",
      "track-android-development",
      "track-data-engineering",
      "track-enterprise-microservices",
      "track-developer-tooling",
      "track-game-development",
    ],
  },
  {
    id: "capstone",
    title: "Capstone Projects (Proof of Fluency)",
    lessonIds: [
      "capstone-cli-tool",
      "capstone-rest-api",
      "capstone-android-app",
      "capstone-data-pipeline",
      "capstone-developer-tool",
    ],
  },
];
